config/routes.rb
TwoHundredTwentyTwo::Application.routes.draw do

  resources :xcode_projects, :only => :index
  resources :repositories, :only => [:index, :new, :create, :update, :destroy]

  resources :developer_certificates, :only => [:edit, :update]
  resources :build_tasks, :only => :index do
    resources :build_task_results, :only => :create
  end
  resources :build_task_results, :only => :show

  resources :build_rules, :only => [:new, :create]
  resources :native_targets, :only => [] do
    resources :build_rules, :expect => [:index, :show]
  end

  resources :provisioning_profiles, :except => [:edit, :update]

  resources :users, :only => [:show, :edit]


  match '/me' => 'user#show'
  match '/users' => 'user#show'
  
  match '/edit_user' => 'user#edit'
  
  match '/sign_in' => 'user#create'
  match '/logout' => 'user#logout'

  match '/delete_user' => 'user#destroy'



  root :to => 'pages#index'

  match '/:service/oauth/start'    => 'oauth#new',    :as => :oauth_authorize
  match '/:service/oauth/callback' => 'oauth#create', :as => :oauth_callback
  match '/access_key' => redirect('/')

  post '/github/webhook' => 'push#create'

end

app/models/xcode_project.rb
class XcodeProject < ActiveRecord::Base

  has_many :native_targets
  has_many :build_rules, :through => :native_targets

  has_many :xcode_project_refs

  has_many :repository_branches, :through => :xcode_project_refs
  has_many :repository_tags,     :through => :xcode_project_refs

  def to_s
    name
  end

end

app/controllers/xcode_projects_controller.rb
class XcodeProjectsController < ApplicationController
  # GET /xcode_projects
  # GET /xcode_projects.json
  def index
    @xcode_projects = current_user.xcode_projects
  end

end

app/helpers/xcode_projects_helper.rb
module XcodeProjectsHelper
end

app/views/xcode_projects/_form.html.erb
<%= simple_form_for(@xcode_project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/xcode_projects/_xcode_project.html.erb
<tr>
  <th rowspan="<%= [xcode_project.native_targets.application_type.count, 1].max %>">
    <%= xcode_project.name %>
  </th>
  <% if xcode_project.native_targets.application_type.count == 0 %>
    <td colspan="4">No targets</td>
  <% else %>
    <%= render [xcode_project.native_targets.application_type.first].compact %>
  <% end %>
</tr>


<% (xcode_project.native_targets.application_type.all - [xcode_project.native_targets.application_type.first]).each do |native_target| %>
  <tr>
    <%= render [native_target] %>
  </tr>
<% end %>

app/views/xcode_projects/edit.html.erb
<h1>Editing xcode_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @xcode_project %> |
<%= link_to 'Back', xcode_projects_path %>

app/views/xcode_projects/index.html.erb
<% content_for :title do %>
  Projects
<% end %>

<table class="table table-striped table-bordered">
  <tr>
    <th>Project</th>
    <th>Target</th>
    <th>Branches</th>
    <th>Rules</th>
  </tr>
<% if  @xcode_projects.any? %>
  <%= render @xcode_projects %>
<% else %>
  <tr>
    <td colspan="4">You don't have any projects yet. Start configuring your projects in the <%= link_to "Repositories tab", :repositories %>.</td>
  </tr>
<% end %>
 
</table>

<%= link_to [:new, :build_rule], :class => 'btn btn-success btn-large' do %>
  <i class="icon-plus"></i> New build rule
<% end %>

app/views/xcode_projects/new.html.erb
<h1>New xcode_project</h1>

<%= render 'form' %>

<%= link_to 'Back', xcode_projects_path %>

app/views/xcode_projects/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_xcode_project_path(@xcode_project) %> |
<%= link_to 'Back', xcode_projects_path %>