config/routes.rb
TwoHundredTwentyTwo::Application.routes.draw do

  resources :xcode_projects, :only => :index
  resources :repositories, :only => [:index, :new, :create, :update, :destroy]

  resources :developer_certificates, :only => [:edit, :update]
  resources :build_tasks, :only => :index do
    resources :build_task_results, :only => :create
  end
  resources :build_task_results, :only => :show

  resources :build_rules, :only => [:new, :create]
  resources :native_targets, :only => [] do
    resources :build_rules, :expect => [:index, :show]
  end

  resources :provisioning_profiles, :except => [:edit, :update]

  resources :users, :only => [:show, :edit]


  match '/me' => 'user#show'
  match '/users' => 'user#show'
  
  match '/edit_user' => 'user#edit'
  
  match '/sign_in' => 'user#create'
  match '/logout' => 'user#logout'

  match '/delete_user' => 'user#destroy'



  root :to => 'pages#index'

  match '/:service/oauth/start'    => 'oauth#new',    :as => :oauth_authorize
  match '/:service/oauth/callback' => 'oauth#create', :as => :oauth_callback
  match '/access_key' => redirect('/')

  post '/github/webhook' => 'push#create'

end

app/models/repository.rb
require 'open-uri'
require "net/https"

class Repository < ActiveRecord::Base

  has_many :tags,     :class_name => 'RepositoryTag', :dependent => :destroy
  has_many :branches, :class_name => 'RepositoryBranch', :dependent => :destroy

  has_many :xcode_projects, :dependent => :destroy

  before_validation :get_details_from_github
  after_create  :fetch_branches, :fetch_tags

  def automatic_builds?
    github_webhook_id? && github_webhook_confirmed?
  end

  def fetch_tags(build = false)
    # get tags
    # https://api.github.com/repos/AppBlade/SDK/tags
    # fetch all by default, all new tags to appear are to be built against
    # only scan new ones for xcodeproj
    JSON.parse(open("https://api.github.com/repos/#{full_name}/tags?oauth_token=#{oauth_token}").read).each do |result|
      tag = tags.where(:name => result['name']).first || tags.new
      new_tag = tag.new_record?
      tag.name = result['name']
      tag.sha  = result['commit']['sha']
      tag.save
      tag.fetch_tree if build && new_tag
    end
  end

  def oauth_token
	ENV['OAUTH_TOKEN']  
  end

  def get_archive_link(ref)
    uri = URI.parse "https://api.github.com/repos/#{full_name}/zipball/#{ref}"
    http = Net::HTTP.new uri.host, uri.port
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new uri.request_uri
    request['Authorization'] = "Bearer #{oauth_token}"
    response = http.request request
    response['Location']
  end

private


  def get_details_from_github
    json = JSON.parse(open("https://api.github.com/repos/#{full_name}?oauth_token=#{oauth_token}").read)
    setup_github_shared_secret if json['permissions']['admin'] && github_shared_secret.nil?
    setup_github_post_commit   if github_shared_secret? && github_shared_secret_changed?
    test_github_post_commit    if github_webhook_id? && !github_webhook_confirmed?
  end

  def setup_github_shared_secret
    self.github_shared_secret = SecureRandom.hex
  end

  def setup_github_post_commit
    uri = URI.parse "https://api.github.com/repos/#{full_name}/hooks"
    http = Net::HTTP.new uri.host, uri.port
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Post.new uri.request_uri
    request['Authorization'] = "Bearer #{oauth_token}"
    post_url = "#{ENV['GITHUB_WEBHOOK_HOST']}/github/webhook" || "#{ENV['GITHUB_WEBHOOK_HOST']}/github/webhook"
    request.body = {name: 'web', events: ['push'], active: true, config: {url: post_url, content_type: 'json', secret: github_shared_secret}}.to_json
    response = http.request request
    json = JSON.parse(response.body)
    self.github_webhook_id = json['id']
    self.github_webhook_confirmed = false
    true
  end

  def test_github_post_commit
    uri = URI.parse "https://api.github.com/repos/#{full_name}/hooks/#{github_webhook_id}/test"
    http = Net::HTTP.new uri.host, uri.port
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Post.new uri.request_uri
    request['Authorization'] = "Bearer #{oauth_token}"
    http.request request
    true
  end

  # branches are manual build processes, scan all of them for xcodeproj
  def fetch_branches
    JSON.parse(open("https://api.github.com/repos/#{full_name}/branches?oauth_token=#{oauth_token}").read).each do |result|
      branch = branches.where(:name => result['name']).first || branches.new
      branch.name = result['name']
      branch.sha  = result['commit']['sha']
      branch.save
    end
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    @repositories = current_user.repositories
  end

  def new
    @repository = current_user.repositories.new
    @github_repositories = []
    @github_repositories |= JSON.parse(open("https://api.github.com/user/repos?per_page=500&oauth_token=#{oauth_token}").read).map {|r| [r['name'], r['full_name'], r['owner']['login']] }
    JSON.parse(open("https://api.github.com/user/orgs?per_page=500&oauth_token=#{oauth_token}").read).each do |result|
      @github_repositories |= JSON.parse(open("https://api.github.com/orgs/#{result['login']}/repos?per_page=500&oauth_token=#{oauth_token}").read).map {|r| [r['name'], r['full_name'], r['owner']['login']] }
    end
  end

  def create
 	repository_full_name = params[:repository][:full_name]
  	if Repository.where(:user_id => current_user.id, :full_name => repository_full_name).count == 0
		@repository = current_user.repositories.new
		@repository.full_name = repository_full_name
		if @repository.save
			if @repository.xcode_projects.count > 0
				redirect_to :xcode_projects
			else
				flash[:warning] = "Could not find any projects in #{@repository.full_name}."  
				redirect_to :repositories
			end
		else
		  render :new
		end
	else
		flash[:warning] = "You already created a link to #{repository_full_name}."  
		redirect_to :repositories
	end
  end

  def update
    @repository = current_user.repositories.find params[:id]
    @repository.save
    redirect_to :repositories
  end

  def destroy
    repository = current_user.repositories.find params[:id]
    flash[:notice] = "#{repository.full_name} removed from Shipbot." unless repository.nil?  
    flash[:error] = "An error occurred and this repository could not be removed" unless repository  

    repository.destroy
    redirect_to :repositories
  end

private


end

app/helpers/repositories_helper.rb
module RepositoriesHelper

  def automatic_build_status(repository)
    if repository.github_webhook_id?
      if repository.github_webhook_confirmed?
        'Will be performed when tags are pushed to Github'
      else
        'Will not be performed yet, we are still waiting on Github to confirm the hooks'
      end
    else
      'Will not be performed, you aren\'t an admin on the Github project'
    end
  end

end

app/views/repositories/_repository.html.erb
<tr>
  <td><%= repository.full_name %></td>
  <td>
    <%= automatic_build_status repository %>
    <% unless repository.automatic_builds? %>
      <%= link_to repository, :method => :put, :class => 'btn btn-small pull-right' do %>
        <i class="icon-refresh"></i> Try again
      <% end %>
    <% end %>
  </td>
  <td><%= pluralize repository.branches.count, 'branch' %></td>
  <td><%= pluralize repository.tags.count, 'tag' %></td>
  <td><%= button_to "Forget", repository, :method=>:delete, :class=>'destroy btn btn-danger' %></td>
</tr>

app/views/repositories/index.html.erb
<% content_for :title do %>
  Repositories
<% end %>

<p>Tracked repositories will be scanned for Xcode Projects, braches, tags, native targets, build configurations, and all kindsa fun stuff. <strong>We will not write to the repository</strong>, only setup a post-commit hook <em>if you have the permissions to allow us</em>.</p>
<p>Manual builds can be fired off from the <%= link_to 'projects page', :xcode_projects %>, for an automatic build just push a tag.</p>

<table class="table table-striped table-bordered">

  <tr>
    <th>Full name</th>
    <th>Automatic builds</th>
    <th colspan="2"></th>
  </tr>
<% if  @repositories.any? %>
  <%= render @repositories %>
<% else %>
  <tr>
    <td colspan="4">You don't have any repositories tracked yet! Track one by clicking below.</td>
  </tr>
<% end %>

</table>

<%= link_to new_repository_path, :class => 'btn btn-success btn-large' do %>
  <i class="icon-plus"></i> Track a new repository
<% end %>

app/views/repositories/new.html.erb
<% content_for :title do %>
  Track a new repository
<% end %>

<%= simple_form_for @repository do |form| %>
  <div class="control-group select optional">
    <label class="select optional control-label" for="repository_full_name">Choose a repository to track</label>
    <div class="controls">
      <select name="repository[full_name]">
        <% @github_repositories.group_by(&:last).each do |login, github_repositories| %>
          <optgroup label="<%= login %>">
            <% github_repositories.each do |github_repository| %>
              <option value="<%= github_repository[1] %>"><%= github_repository[0] %></option>
            <% end %>
          </optgroup>
        <% end %>
      </select>
    </div>
  </div>
  <%= form.submit 'Track repository and fetch details', :class => 'btn btn-primary' %>
<% end %>