config/routes.rb
TwoHundredTwentyTwo::Application.routes.draw do

  resources :xcode_projects, :only => :index
  resources :repositories, :only => [:index, :new, :create, :update, :destroy]

  resources :developer_certificates, :only => [:edit, :update]
  resources :build_tasks, :only => :index do
    resources :build_task_results, :only => :create
  end
  resources :build_task_results, :only => :show

  resources :build_rules, :only => [:new, :create]
  resources :native_targets, :only => [] do
    resources :build_rules, :expect => [:index, :show]
  end

  resources :provisioning_profiles, :except => [:edit, :update]

  resources :users, :only => [:show, :edit]


  match '/me' => 'user#show'
  match '/users' => 'user#show'
  
  match '/edit_user' => 'user#edit'
  
  match '/sign_in' => 'user#create'
  match '/logout' => 'user#logout'

  match '/delete_user' => 'user#destroy'



  root :to => 'pages#index'

  match '/:service/oauth/start'    => 'oauth#new',    :as => :oauth_authorize
  match '/:service/oauth/callback' => 'oauth#create', :as => :oauth_callback
  match '/access_key' => redirect('/')

  post '/github/webhook' => 'push#create'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :repositories,           :dependent => :destroy
  has_many :provisioning_profiles,  :dependent => :destroy
  has_many :developer_certificates, :dependent => :destroy

  has_many :xcode_projects, :through => :repositories

  has_many :access_keys,   :dependent => :destroy, :as => :owner
  has_many :user_sessions, :dependent => :destroy

  before_create :gather_info_from_provider

  accepts_nested_attributes_for :access_keys
  
  attr_accessible :access_keys_attributes

  def build_tasks
    BuildTask.joins(:build_rule => :native_target).where(:native_targets => {:xcode_project_id => xcode_projects})
  end

  def native_targets
    NativeTarget.where(:xcode_project_id => xcode_projects)
  end

  def gather_info_from_provider
  			conn = Faraday.new "https://api.github.com/", ssl: {verify: false} 
			result = conn.get "/user?oauth_token=#{access_keys.first.token_a}"
	result_body = JSON.parse(result.body)
	puts result_body	
  	self.name = result_body['login']
  	self.email = result_body['email']
  end
  
  
  def to_s
  	name
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def create
	
	end
	
	def show
		@access_keys = current_user.access_keys
	end
	
	def edit
	
	end
	
	def destroy 
		if current_user.id && params[:confirm_id]
			User.find(current_user.id).destroy
	    	session[:user_session_id] = nil
    		flash[:notice] = "Account Deleted. Sorry to see you go!"
    		redirect_to root_url
    	else
    		redirect_to users_url
    		flash[:error] = "You do not have access to do that."
		end
	end
end

app/helpers/user_helper.rb
module UserHelper

 def time_since(date_time)
	string_frmt = "%l:%M %p today" if date_time.today?
	string_frmt ||= "%A" if (Time.now - date_time) < 7.days 
	string_frmt ||= "%b %d" if (Time.now - date_time) < 1.month
	string_frmt ||= "%m/%d/%Y"
	return date_time.strftime(string_frmt) unless string_frmt == "%b %d"
	date_time.strftime(string_frmt).ordinalize
 end

  def main_provider(user)
	if user.access_keys.count > 0
  		user.access_keys.first.service
  	else
  		'no known provider'
	end
  end

  def main_provider_icon(user)
	if main_provider(user) == 'github'
		return 'icon-github'
	else
		return 'icon-cog'
	end
  end


end

app/views/user/_access_key.html.erb
<tr>
  <td><%= access_key.service.capitalize %></td>
  <td><%= access_key.access_token %></td>
  <td><%= time_ago_in_words access_key.updated_at %> ago</td>
  <td>Valid</td>
  <td colspan="2"><%= link_to 'Refresh', '/user', :class=>'btn btn-info pull-left' %>  <%= link_to 'Forget', '/user', :class=>'btn btn-danger pull-right' %></td>
</tr>

app/views/user/_form.html.erb
<%= simple_form_for @current_user do |form| %>

<% end %>

app/views/user/edit.html.erb
<% content_for :title do %>
  Edit <%= @native_target %> build rule
<% end %>

<%= render 'form' %>

<%= link_to [:new, @native_target, @build_rule], :class => 'btn' do %>
  <i class="icon-plus"></i> Or add another build rule
<% end %>

app/views/user/show.html.erb
<% content_for :title do %>
  <%= current_user %>
<% end %>
  <h5><%= current_user.email %></h5>
  <p>User since <%= time_since current_user.created_at %> <i>(all time is in UTC)</i></p> <%= link_to 'Logout', '/logout', :class=>'btn btn-danger pull-right' %>
<br/>
<table class="table table-striped table-bordered" style="min-width: 940px;">
  <h4>Access Keys</h4>
  <tr>
    <th>Provider</th>
    <th>Token</th>
    <th>Last Seen</th>
    <th>Status</th>
    <th colspan="2">Actions</th>
  </tr>

<%= render :partial => "access_key", :collection => @access_keys %>
</table>

<%= link_to '+ New Access Key', '/users', :class=>'btn btn-success' %>

<%= link_to 'Delete My Account', delete_user_path(:confirm_id=>current_user.id), :confirm=>"Are you sure you want to delete your account? This isn't reversible!", :class=>'btn btn-danger pull-right', :style=>"margin-top:3em;" %>