config/routes.rb
TwoHundredTwentyTwo::Application.routes.draw do

  resources :xcode_projects, :only => :index
  resources :repositories, :only => [:index, :new, :create, :update, :destroy]

  resources :developer_certificates, :only => [:edit, :update]
  resources :build_tasks, :only => :index do
    resources :build_task_results, :only => :create
  end
  resources :build_task_results, :only => :show

  resources :build_rules, :only => [:new, :create]
  resources :native_targets, :only => [] do
    resources :build_rules, :expect => [:index, :show]
  end

  resources :provisioning_profiles, :except => [:edit, :update]

  resources :users, :only => [:show, :edit]


  match '/me' => 'user#show'
  match '/users' => 'user#show'
  
  match '/edit_user' => 'user#edit'
  
  match '/sign_in' => 'user#create'
  match '/logout' => 'user#logout'

  match '/delete_user' => 'user#destroy'



  root :to => 'pages#index'

  match '/:service/oauth/start'    => 'oauth#new',    :as => :oauth_authorize
  match '/:service/oauth/callback' => 'oauth#create', :as => :oauth_callback
  match '/access_key' => redirect('/')

  post '/github/webhook' => 'push#create'

end

app/models/provisioning_profile.rb
class ProvisioningProfile < ActiveRecord::Base

  attr_accessible :mobileprovision
  
  mount_uploader :mobileprovision, MobileprovisionUploader

  belongs_to :developer_certificate

  validates :uuid, :uniqueness => true

  def unqualified_application_identifier
    application_identifier.gsub "#{application_identifier_prefix.strip}.", ''
  end

  def to_s
    name
  end

end

app/controllers/provisioning_profiles_controller.rb
class ProvisioningProfilesController < ApplicationController
  # GET /provisioning_profiles
  # GET /provisioning_profiles.json
  def index
    @provisioning_profiles = current_user.provisioning_profiles
  end

  # GET /provisioning_profiles/1
  # GET /provisioning_profiles/1.json
  def show
    @provisioning_profile = current_user.provisioning_profiles.find(params[:id])
  end

  # GET /provisioning_profiles/new
  # GET /provisioning_profiles/new.json
  def new
    @provisioning_profile = current_user.provisioning_profiles.new
  end

  # POST /provisioning_profiles
  # POST /provisioning_profiles.json
  def create
    @provisioning_profile = current_user.provisioning_profiles.new(params[:provisioning_profile])

    if @provisioning_profile.save
      redirect_to provisioning_profiles_url, notice: 'Provisioning profile was successfully created.'
    else
      render action: "new"
    end
  end

  # DELETE /provisioning_profiles/1
  # DELETE /provisioning_profiles/1.json
  def destroy
    @provisioning_profile = current_user.provisioning_profiles.find(params[:id])
    @provisioning_profile.destroy
    redirect_to provisioning_profiles_url
  end
end

app/helpers/provisioning_profiles_helper.rb
module ProvisioningProfilesHelper
end

app/views/provisioning_profiles/_form.html.erb
<%= simple_form_for(@provisioning_profile, :multipart => true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :mobileprovision, :as => :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/provisioning_profiles/_provisioning_profile.html.erb
<tr>
  <td><%= provisioning_profile.name %></td>
  <td><%=  provisioning_profile.developer_certificate  %>
  <td><%= time_ago_in_words provisioning_profile.expires_at %></td>
  <td><%= provisioning_profile.unqualified_application_identifier %></td>
  <td>
    <% if provisioning_profile.enterprise %>
      &#8734;
    <% else %>
      <%= provisioning_profile.provisioned_devices_count %>
    <% end %>
  </td>
  <td>
    <% if provisioning_profile.developer_certificate.keychain_export? %>
      Provided, ready to sign applications
    <% else %>
      <%= link_to 'Not provided, this is needed to sign applications', [:edit, provisioning_profile.developer_certificate] %>
    <% end %>
  </td>
  <td><%= link_to 'Details', provisioning_profile %></td>
  <td><%= link_to 'Destroy', provisioning_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/provisioning_profiles/index.html.erb
<% content_for :title do %>
  Provisioning Profiles
<% end %>

<table class="table table-striped table-bordered">

  <tr>
    <th>Name</th>
    <th>Certificate</th>
    <th>Expires in</th>
    <th>Application identifier</th>
    <th>Devices</th>
    <th></th>
    <th></th>
  </tr>
<% if @provisioning_profiles.any? %>
  <%= render @provisioning_profiles %>
<% else %>
    <tr>
    <td colspan="7">You don't have any provsioning profiles. Upload one by clicking below.</td>
  </tr>
<% end %>

</table>

<%= link_to new_provisioning_profile_path, :class => 'btn btn-success btn-large' do %>
  <i class="icon-plus"></i> New Provisioning profile
<% end %>

app/views/provisioning_profiles/new.html.erb
<h1>New provisioning_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', provisioning_profiles_path %>

app/views/provisioning_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uuid:</b>
  <%= @provisioning_profile.uuid %>
</p>

<p>
  <b>Name:</b>
  <%= @provisioning_profile.name %>
</p>

<p>
  <b>Issued at:</b>
  <%= @provisioning_profile.issued_at %>
</p>

<p>
  <b>Expires at:</b>
  <%= @provisioning_profile.expires_at %>
</p>

<p>
  <b>Enterprise:</b>
  <%= @provisioning_profile.enterprise %>
</p>

<p>
  <b>Application identifier:</b>
  <%= @provisioning_profile.application_identifier %>
</p>

<p>
  <b>Team identifier:</b>
  <%= @provisioning_profile.team_identifier %>
</p>

<p>
  <b>Application identifier prefix:</b>
  <%= @provisioning_profile.application_identifier_prefix %>
</p>

<p>
  <b>Mobileprovision:</b>
  <%= @provisioning_profile.mobileprovision %>
</p>

<p>
  <b>Provisioned devices count:</b>
  <%= @provisioning_profile.provisioned_devices_count %>
</p>

<%= link_to 'Back', provisioning_profiles_path %>